when:
  - event: push
    branch: main

steps:
  deploy:
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "Deploying from Woodpecker workspace"
      - pwd
      - ls -la

      # IMPORTANT: stay in workspace (no cd to /home)
      - docker compose up -d --build
