when:
  - event: push
    branch: main

steps:
  install:
    image: node:22
    commands:
      - npm install

  test:
    image: node:22
    commands:
      - npm run test

  build:
    image: node:22
    commands:
      - npm run build
