when:
  - event: push
    branch: main

steps:
  install:
    image: node:22
    commands:
      - npm ci

  # test:
  #   image: node:22
  #   commands:
  #     - npm run test

  build:
    image: node:22
    commands:
      - npm run build

  deploy:
    image: docker:cli
    commands:
      - cd /home/abdulwahid/app/nest_backend
      - git fetch origin
      - git reset --hard origin/main
      - docker compose up -d --build
